// Copyright 2026 Adobe. All rights reserved.
// This file is licensed to you under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may obtain a copy
// of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
// OF ANY KIND, either express or implied. See the License for the specific language
// governing permissions and limitations under the License.

//! Native Swift bindings for `design-data-core` via UniFFI.
//!
//! This crate exposes the full Spectrum design-data [`Dataset`] API —
//! query, resolve, validate, diff, suggest, and primer — as an idiomatic Swift
//! class, distributed as an XCFramework + Swift Package.
//!
//! # Data embedding
//!
//! When built with `--features embedded`, the canonical Spectrum token dataset
//! is baked into the binary as a prebuilt `.redb` cache blob and loaded
//! in-memory via [`design_data_core::cache::load_from_bytes`].  No filesystem
//! writes occur — the `.app` sandbox is fully respected.
//!
//! Build the blob first:
//! ```sh
//! moon run sdk-swift:cache-build
//! ```
//!
//! Then build the XCFramework:
//! ```sh
//! node sdk/swift/scripts/build-swift.mjs
//! ```
//!
//! # API surface
//!
//! All public items below are exported to Swift via the `#[uniffi::export]` and
//! `#[derive(uniffi::*)]` proc-macros. The generated `DesignDataSwift.swift` file
//! (emitted by `uniffi-bindgen generate --language swift`) is the primary Swift
//! integration point.

use std::collections::HashMap;
#[cfg(feature = "embedded")]
use std::sync::OnceLock;

use design_data_core::cascade::{resolve_property, resolve_reference, ResolutionContext};
use design_data_core::diff::semantic_diff;
use design_data_core::graph::TokenGraph;
use design_data_core::primer;
use design_data_core::query;
use design_data_core::suggest;
use design_data_core::validate::relational::validate_relational;

// UniFFI scaffolding — generates the C-ABI entry points consumed by the generated
// Swift/Kotlin glue code.  Must appear before any `#[uniffi::export]` items.
uniffi::setup_scaffolding!();

// ---------------------------------------------------------------------------
// Embedded cache blob
// ---------------------------------------------------------------------------

/// The prebuilt `.redb` cache of the canonical Spectrum dataset.
///
/// Generated by `moon run sdk-swift:cache-build`; embedded at compile time.
/// A `OnceLock` ensures the cache is opened at most once per process.
#[cfg(feature = "embedded")]
static EMBEDDED_GRAPH: OnceLock<Result<TokenGraph, String>> = OnceLock::new();

#[cfg(feature = "embedded")]
static EMBEDDED_CACHE_BYTES: &[u8] = {
    // Emit a clear compile-time error if the blob has not been generated rather
    // than silently producing an unusable binary.
    //
    // To generate: `moon run sdk-swift:cache-build`
    // (or `cargo run -p design-data-cli -- cache-build packages/design-data/tokens ...`)
    if false {
        panic!("embedded_cache.redb not found — run `moon run sdk-swift:cache-build` first");
    }
    include_bytes!("embedded_cache.redb")
};

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

/// Errors that can be returned from [`Dataset`] operations.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum DataError {
    /// The embedded cache blob was not compiled in (build without `--features embedded`).
    #[error("Embedded cache not available — build with `--features embedded` and run `moon run sdk-swift:cache-build`")]
    EmbeddedNotAvailable,

    /// The embedded cache blob could not be opened.
    #[error("Failed to open embedded cache: {message}")]
    CacheOpen { message: String },

    /// The supplied token JSON could not be parsed.
    #[error("Failed to parse token JSON: {message}")]
    ParseError { message: String },

    /// A query expression was malformed.
    #[error("Invalid query expression: {message}")]
    QueryError { message: String },

    /// An internal serialization error.
    #[error("Serialization error: {message}")]
    SerializeError { message: String },
}

// ---------------------------------------------------------------------------
// Record types — mirrors sdk/wasm/src/types.rs with serde_json::Value
//   serialised as JSON strings so uniffi can cross the FFI boundary.
// ---------------------------------------------------------------------------

/// A single token record as returned by query results.
///
/// `raw` is the full source JSON of the token (all fields: name, value, uuid,
/// `$schema`, etc.) serialised as a JSON string for easy `Codable` decoding on
/// the Swift side.
#[derive(Debug, Clone, uniffi::Record)]
pub struct TokenResult {
    /// The canonical dot-path name of the token (e.g. `"color.accent.background.default.light"`).
    pub name: String,
    /// Full source JSON of the token — decode with `JSONDecoder` / `Codable`.
    pub raw: String,
    pub uuid: Option<String>,
    pub schema_url: Option<String>,
    pub alias_target: Option<String>,
    /// Layer this token belongs to (e.g. `"foundation"`, `"platform"`, `"component"`).
    pub layer: String,
}

/// A single resolved token result from [`Dataset::resolve`].
#[derive(Debug, Clone, uniffi::Record)]
pub struct ResolveResult {
    pub token: TokenResult,
    /// Cascade specificity score — higher means this token is a more precise match.
    pub specificity: u32,
}

/// The terminal value and traversal chain from [`Dataset::resolve_reference`].
#[derive(Debug, Clone, uniffi::Record)]
pub struct ReferenceChainResult {
    /// The resolved terminal value serialised as JSON (may be a string, number, or object).
    pub value: Option<String>,
    /// Ordered list: original reference → intermediate names → final value.
    pub chain: Vec<String>,
}

/// Severity level of a validation diagnostic.
#[derive(Debug, Clone, uniffi::Enum)]
pub enum Severity {
    Error,
    Warning,
    Info,
}

/// A single validation diagnostic.
#[derive(Debug, Clone, uniffi::Record)]
pub struct Diagnostic {
    pub severity: Severity,
    pub message: String,
    pub rule_id: Option<String>,
    /// Token path or instance path the diagnostic applies to.
    pub path: Option<String>,
}

/// The aggregate result of [`Dataset::validate`].
#[derive(Debug, Clone, uniffi::Record)]
pub struct ValidationResult {
    pub valid: bool,
    pub errors: Vec<Diagnostic>,
    pub warnings: Vec<Diagnostic>,
}

/// A key→value change within a token's properties.
#[derive(Debug, Clone, uniffi::Record)]
pub struct PropertyChange {
    pub path: String,
    /// One of `"added"`, `"removed"`, `"modified"`.
    pub change_type: String,
    /// New value as a JSON string (present when `change_type` is `"added"` or `"modified"`).
    pub new_value: Option<String>,
    /// Original value as a JSON string (present when `change_type` is `"removed"` or `"modified"`).
    pub original_value: Option<String>,
}

/// A token that was renamed (same UUID, different name).
#[derive(Debug, Clone, uniffi::Record)]
pub struct RenamedToken {
    pub old_name: String,
    pub new_name: String,
    pub uuid: Option<String>,
    pub property_changes: Vec<PropertyChange>,
}

/// A token that was added in the newer dataset.
#[derive(Debug, Clone, uniffi::Record)]
pub struct AddedToken {
    pub name: String,
    pub uuid: Option<String>,
}

/// A token that was removed from the newer dataset.
#[derive(Debug, Clone, uniffi::Record)]
pub struct DeletedToken {
    pub name: String,
    pub uuid: Option<String>,
}

/// A token that gained a `deprecated` marker.
#[derive(Debug, Clone, uniffi::Record)]
pub struct DeprecatedToken {
    pub name: String,
    pub uuid: Option<String>,
}

/// A token that had its `deprecated` marker removed.
#[derive(Debug, Clone, uniffi::Record)]
pub struct RevertedToken {
    pub name: String,
    pub uuid: Option<String>,
}

/// A token that had property-level changes (same name, same UUID).
#[derive(Debug, Clone, uniffi::Record)]
pub struct UpdatedToken {
    pub name: String,
    pub uuid: Option<String>,
    pub property_changes: Vec<PropertyChange>,
}

/// The result of [`Dataset::diff`].
#[derive(Debug, Clone, uniffi::Record)]
pub struct DiffResult {
    pub renamed: Vec<RenamedToken>,
    pub deprecated: Vec<DeprecatedToken>,
    pub reverted: Vec<RevertedToken>,
    pub added: Vec<AddedToken>,
    pub deleted: Vec<DeletedToken>,
    pub updated: Vec<UpdatedToken>,
}

/// A single ranked suggestion result from [`Dataset::suggest`].
#[derive(Debug, Clone, uniffi::Record)]
pub struct SuggestResult {
    pub token_uuid: Option<String>,
    pub token_name: String,
    pub file: String,
    pub layer: String,
    /// Jaccard similarity score in [0, 1].
    pub confidence: f32,
    /// Full name-object JSON (decode with `Codable` for structured access).
    pub name_object: Option<String>,
    /// Token value serialised as JSON.
    pub value: Option<String>,
}

// ---------------------------------------------------------------------------
// Conversion helpers
// ---------------------------------------------------------------------------

fn json_to_string(v: &serde_json::Value) -> String {
    v.to_string()
}

fn opt_json_to_string(v: &Option<serde_json::Value>) -> Option<String> {
    v.as_ref().map(json_to_string)
}

impl From<&design_data_core::graph::TokenRecord> for TokenResult {
    fn from(r: &design_data_core::graph::TokenRecord) -> Self {
        Self {
            name: r.name.clone(),
            raw: json_to_string(&r.raw),
            uuid: r.uuid.clone(),
            schema_url: r.schema_url.clone(),
            alias_target: r.alias_target.clone(),
            layer: format!("{:?}", r.layer).to_lowercase(),
        }
    }
}

impl From<&design_data_core::report::Severity> for Severity {
    fn from(s: &design_data_core::report::Severity) -> Self {
        match s {
            design_data_core::report::Severity::Error => Severity::Error,
            design_data_core::report::Severity::Warning => Severity::Warning,
            design_data_core::report::Severity::Info => Severity::Info,
        }
    }
}

impl From<&design_data_core::report::Diagnostic> for Diagnostic {
    fn from(d: &design_data_core::report::Diagnostic) -> Self {
        Self {
            severity: Severity::from(&d.severity),
            message: d.message.clone(),
            rule_id: d.rule_id.clone(),
            path: d.instance_path.clone().or_else(|| d.token.clone()),
        }
    }
}

impl From<design_data_core::report::ValidationReport> for ValidationResult {
    fn from(r: design_data_core::report::ValidationReport) -> Self {
        // NOTE: `ValidationReport.errors` holds ALL diagnostics regardless of severity
        // (there is no separate `warnings` field in core — see sdk/core/src/report.rs).
        // Split into two arrays by filtering the same slice twice.
        let errors = r
            .errors
            .iter()
            .filter(|d| matches!(d.severity, design_data_core::report::Severity::Error))
            .map(Diagnostic::from)
            .collect();
        let warnings = r
            .errors
            .iter()
            .filter(|d| {
                matches!(
                    d.severity,
                    design_data_core::report::Severity::Warning
                        | design_data_core::report::Severity::Info
                )
            })
            .map(Diagnostic::from)
            .collect();
        Self {
            valid: r.valid,
            errors,
            warnings,
        }
    }
}

impl From<design_data_core::suggest::SuggestionResult> for SuggestResult {
    fn from(r: design_data_core::suggest::SuggestionResult) -> Self {
        Self {
            token_uuid: r.token_uuid,
            token_name: r.token_name,
            file: r.file.to_string_lossy().into_owned(),
            layer: format!("{:?}", r.layer).to_lowercase(),
            confidence: r.confidence,
            name_object: opt_json_to_string(&r.name_object),
            value: opt_json_to_string(&r.value),
        }
    }
}

fn map_property_change(c: &design_data_core::diff::PropertyChange) -> PropertyChange {
    PropertyChange {
        path: c.path.clone(),
        change_type: format!("{:?}", c.change_type).to_lowercase(),
        new_value: opt_json_to_string(&c.new_value),
        original_value: opt_json_to_string(&c.original_value),
    }
}

// ---------------------------------------------------------------------------
// Dataset — the primary Swift-facing object
// ---------------------------------------------------------------------------

/// How a `Dataset` was constructed — determines the `primer` provenance field.
enum DatasetSource {
    /// Loaded from the embedded `.redb` blob compiled into the binary.
    ///
    /// Only reachable when the `embedded` feature is enabled.
    #[cfg_attr(not(feature = "embedded"), allow(dead_code))]
    Embedded,
    /// Constructed in-memory from caller-supplied token JSON.
    InMemory,
}

/// A loaded Spectrum token dataset you can query, validate, resolve, and diff.
///
/// # Usage (Swift)
///
/// ```swift
/// import DesignData
///
/// // Use the canonical embedded Spectrum dataset (built with --features embedded):
/// let ds = try Dataset.embedded()
/// let hits = try ds.query(expr: "property=color,colorScheme=dark")
///
/// // Or build from your own token JSON:
/// let json = try String(contentsOf: url)
/// let ds2 = try Dataset.fromTokens(json: json)
/// ```
#[derive(uniffi::Object)]
pub struct Dataset {
    graph: TokenGraph,
    source: DatasetSource,
}

#[uniffi::export]
impl Dataset {
    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    /// Open the canonical embedded Spectrum dataset from the prebuilt cache.
    ///
    /// The cache is opened once and reused; subsequent calls are cheap.
    ///
    /// Throws [`DataError::EmbeddedNotAvailable`] if built without
    /// `--features embedded`, or [`DataError::CacheOpen`] if the blob is corrupt.
    #[uniffi::constructor]
    pub fn embedded() -> Result<std::sync::Arc<Dataset>, DataError> {
        #[cfg(feature = "embedded")]
        {
            use design_data_core::cache;
            let graph = EMBEDDED_GRAPH
                .get_or_init(|| {
                    cache::load_from_bytes(EMBEDDED_CACHE_BYTES).map_err(|e| e.to_string())
                })
                .as_ref()
                .map_err(|msg| DataError::CacheOpen {
                    message: msg.clone(),
                })?
                .clone();
            Ok(std::sync::Arc::new(Dataset {
                graph,
                source: DatasetSource::Embedded,
            }))
        }
        #[cfg(not(feature = "embedded"))]
        {
            Err(DataError::EmbeddedNotAvailable)
        }
    }

    /// Build a dataset from a JSON string containing an array of raw token objects.
    ///
    /// Accepts the same format as the cascade token JSON files — an array of token
    /// objects each with a `name` object (e.g. `{ "name": { "property": "..." }, "value": ... }`).
    ///
    /// # Parameters
    /// - `json`: a JSON string containing an array of token objects.
    ///
    /// Throws [`DataError::ParseError`] if the JSON is malformed or not an array.
    #[uniffi::constructor(name = "fromTokens")]
    pub fn from_tokens(json: String) -> Result<std::sync::Arc<Dataset>, DataError> {
        let tokens: Vec<serde_json::Value> =
            serde_json::from_str(&json).map_err(|e| DataError::ParseError {
                message: e.to_string(),
            })?;

        let pairs: Vec<(String, std::path::PathBuf, serde_json::Value)> = tokens
            .into_iter()
            .enumerate()
            .map(|(i, raw)| {
                let key = raw
                    .get("uuid")
                    .and_then(|v| v.as_str())
                    .map(String::from)
                    .unwrap_or_else(|| format!("token-{i}"));
                (key, std::path::PathBuf::from("input.json"), raw)
            })
            .collect();

        let graph = TokenGraph::from_pairs(pairs);
        Ok(std::sync::Arc::new(Dataset {
            graph,
            source: DatasetSource::InMemory,
        }))
    }

    // -----------------------------------------------------------------------
    // Primer
    // -----------------------------------------------------------------------

    /// Emit a structural overview of the dataset for tooling / agent context.
    ///
    /// Returns a JSON string with keys: `specVersion`, `tokenCount`, `modeSets`,
    /// `components`, `taxonomyFields`, `manifest`, `provenance`.
    /// Decode with `JSONDecoder` / `Codable` on the Swift side.
    ///
    /// Throws [`DataError::SerializeError`] if serialization fails (unlikely).
    pub fn primer(&self) -> Result<String, DataError> {
        let provenance = match self.source {
            DatasetSource::Embedded => serde_json::json!({
                "source": "embedded",
                "tokensVersion": primer::EMBEDDED_DATA_VERSION,
            }),
            DatasetSource::InMemory => serde_json::json!({ "source": "in-memory" }),
        };
        let data = primer::build(&self.graph, provenance);
        serde_json::to_string(&data).map_err(|e| DataError::SerializeError {
            message: e.to_string(),
        })
    }

    // -----------------------------------------------------------------------
    // Query
    // -----------------------------------------------------------------------

    /// Filter tokens using a query expression.
    ///
    /// **Syntax:** `key=value` pairs separated by `,` (AND) or `|` (OR).
    /// Use `!=` for negation and `*` as a wildcard suffix or prefix.
    /// Valid keys: `property`, `component`, `variant`, `state`, `colorScheme`,
    /// `scale`, `contrast`, `uuid`, `$schema`.
    ///
    /// Pass an empty string to return all tokens.
    ///
    /// Throws [`DataError::QueryError`] if the expression is malformed.
    pub fn query(&self, expr: String) -> Result<Vec<TokenResult>, DataError> {
        let filter = query::parse(&expr).map_err(|e| DataError::QueryError {
            message: e.to_string(),
        })?;
        let records = query::filter(&self.graph, &filter);
        Ok(records.iter().map(|r| TokenResult::from(*r)).collect())
    }

    // -----------------------------------------------------------------------
    // Suggest
    // -----------------------------------------------------------------------

    /// Rank existing tokens by similarity to a natural-language `intent` string.
    ///
    /// Uses Jaccard similarity over the bag-of-words formed from each token's
    /// key segments, name-object field values, and description text.
    ///
    /// # Parameters
    /// - `intent`: natural-language description (e.g. `"primary button background"`).
    /// - `property_hint`: optionally constrain to tokens with a specific property.
    /// - `limit`: maximum number of results to return.
    pub fn suggest(
        &self,
        intent: String,
        property_hint: Option<String>,
        limit: u32,
    ) -> Vec<SuggestResult> {
        suggest::suggest(
            &self.graph,
            &intent,
            property_hint.as_deref(),
            limit as usize,
        )
        .into_iter()
        .map(SuggestResult::from)
        .collect()
    }

    // -----------------------------------------------------------------------
    // Validate
    // -----------------------------------------------------------------------

    /// Run relational validation rules over the dataset.
    ///
    /// Returns a [`ValidationResult`] with `valid`, `errors`, and `warnings`.
    /// This runs the same rules as `design-data validate` but without structural
    /// (JSON Schema) checks — those require filesystem access.  Build
    /// `design-data-core` with `--features schema-resolvers` and use the CLI for
    /// full structural validation.
    pub fn validate(&self) -> ValidationResult {
        let report = validate_relational(&self.graph, &std::collections::HashSet::new(), None);
        ValidationResult::from(report)
    }

    // -----------------------------------------------------------------------
    // Resolve
    // -----------------------------------------------------------------------

    /// Resolve the winning token for a given `property` in a specific `context`.
    ///
    /// The `context` map maps mode-set names to their active mode values, e.g.:
    /// `["colorScheme": "dark", "scale": "medium"]`.
    ///
    /// Returns the winning token record plus its specificity, or `nil` if no token
    /// matches the property + context combination.
    pub fn resolve(
        &self,
        property: String,
        context: HashMap<String, String>,
    ) -> Option<ResolveResult> {
        let mut ctx = ResolutionContext::new();
        for (k, v) in &context {
            ctx = ctx.with(k.clone(), v.clone());
        }
        resolve_property(&self.graph, &property, &ctx)
            .into_iter()
            .find(|c| c.is_winner)
            .map(|winner| ResolveResult {
                token: TokenResult::from(&winner.record),
                specificity: winner.specificity,
            })
    }

    /// Resolve a legacy token reference by slug in a given context.
    ///
    /// Returns the terminal value and the full alias chain, or `nil` if the
    /// reference cannot be resolved.
    ///
    /// Context keys mirror cascade name-object fields:
    /// - `"colorScheme"` → `"light"` | `"dark"` | `"wireframe"`
    /// - `"scale"` → `"desktop"` | `"mobile"`
    #[uniffi::method(name = "resolveReference")]
    pub fn resolve_reference(
        &self,
        token_ref: String,
        context: HashMap<String, String>,
    ) -> Option<ReferenceChainResult> {
        resolve_reference(&self.graph, &token_ref, &context).map(|r| ReferenceChainResult {
            value: r.value.as_ref().map(json_to_string),
            chain: r.chain,
        })
    }

    // -----------------------------------------------------------------------
    // Diff
    // -----------------------------------------------------------------------

    /// Compute the semantic diff between this dataset and another.
    ///
    /// Returns a [`DiffResult`] with arrays of renamed, deprecated, reverted,
    /// added, deleted, and updated tokens.
    pub fn diff(&self, other: std::sync::Arc<Dataset>) -> DiffResult {
        let report = semantic_diff(&self.graph, &other.graph);

        DiffResult {
            renamed: report
                .renamed
                .iter()
                .map(|r| RenamedToken {
                    old_name: r.old_name.clone(),
                    new_name: r.new_name.clone(),
                    uuid: r.uuid.clone(),
                    property_changes: r.property_changes.iter().map(map_property_change).collect(),
                })
                .collect(),
            deprecated: report
                .deprecated
                .iter()
                .map(|r| DeprecatedToken {
                    name: r.name.clone(),
                    uuid: r.uuid.clone(),
                })
                .collect(),
            reverted: report
                .reverted
                .iter()
                .map(|r| RevertedToken {
                    name: r.name.clone(),
                    uuid: r.uuid.clone(),
                })
                .collect(),
            added: report
                .added
                .iter()
                .map(|r| AddedToken {
                    name: r.name.clone(),
                    uuid: r.uuid.clone(),
                })
                .collect(),
            deleted: report
                .deleted
                .iter()
                .map(|r| DeletedToken {
                    name: r.name.clone(),
                    uuid: r.uuid.clone(),
                })
                .collect(),
            updated: report
                .updated
                .iter()
                .map(|r| UpdatedToken {
                    name: r.name.clone(),
                    uuid: r.uuid.clone(),
                    property_changes: r.property_changes.iter().map(map_property_change).collect(),
                })
                .collect(),
        }
    }

    // -----------------------------------------------------------------------
    // Introspection
    // -----------------------------------------------------------------------

    /// Return the number of tokens in the dataset.
    #[uniffi::method(name = "tokenCount")]
    pub fn token_count(&self) -> u64 {
        self.graph.tokens.len() as u64
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(feature = "embedded")]
    #[test]
    fn embedded_loads_and_has_tokens() {
        let ds = Dataset::embedded().expect("embedded() should succeed");
        assert!(
            ds.token_count() > 0,
            "embedded dataset should have at least one token"
        );
    }

    #[cfg(feature = "embedded")]
    #[test]
    fn query_color_tokens() {
        let ds = Dataset::embedded().expect("embedded() should succeed");
        let results = ds
            .query("property=color".into())
            .expect("query should succeed");
        assert!(
            !results.is_empty(),
            "query for property=color should return results"
        );
        for r in &results {
            assert_eq!(r.layer.is_empty(), false, "layer should be set");
        }
    }

    #[cfg(feature = "embedded")]
    #[test]
    fn resolve_returns_winner() {
        let ds = Dataset::embedded().expect("embedded() should succeed");
        let ctx = [
            ("colorScheme".to_string(), "dark".to_string()),
            ("scale".to_string(), "desktop".to_string()),
        ]
        .into_iter()
        .collect();
        // "background" is a well-known property in Spectrum tokens.
        let result = ds.resolve("background".into(), ctx);
        // May be None if the property name changed — accept either outcome in a unit test.
        if let Some(r) = result {
            assert!(r.specificity > 0);
        }
    }

    #[test]
    fn from_tokens_roundtrip() {
        // Note: avoid '#' inside r# raw strings; use a plain color value instead.
        let json = "[{\"name\":{\"property\":\"color\"},\"value\":\"red\",\"uuid\":\"test-1\"}]";
        let ds = Dataset::from_tokens(json.to_string()).expect("from_tokens should succeed");
        assert_eq!(ds.token_count(), 1);
        let results = ds
            .query("property=color".into())
            .expect("query should succeed");
        assert_eq!(results.len(), 1);
    }

    #[test]
    fn from_tokens_rejects_bad_json() {
        let result = Dataset::from_tokens("not json".to_string());
        assert!(
            matches!(result, Err(DataError::ParseError { .. })),
            "malformed JSON should produce ParseError"
        );
    }
}
