// Copyright 2026 Adobe. All rights reserved.
// This file is licensed to you under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may obtain a copy
// of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
// OF ANY KIND, either express or implied. See the License for the specific language
// governing permissions and limitations under the License.

//! Design system registry data embedded at compile time.
//!
//! Each registry JSON file from `packages/design-system-registry/registry/` is included
//! via `include_str!` and parsed into `HashSet<String>` lookups keyed by value ID.
//! This avoids runtime filesystem access and keeps the validator self-contained.

use std::collections::HashSet;

use serde_json::Value;

/// Parsed registry data for SPEC-009 enum validation.
#[derive(Debug, Clone)]
pub struct RegistryData {
    pub components: HashSet<String>,
    pub states: HashSet<String>,
    pub variants: HashSet<String>,
    pub sizes: HashSet<String>,
    pub anatomy: HashSet<String>,
    pub token_objects: HashSet<String>,
    pub structures: HashSet<String>,
    pub substructures: HashSet<String>,
    pub orientations: HashSet<String>,
    pub positions: HashSet<String>,
    pub densities: HashSet<String>,
    pub shapes: HashSet<String>,
}

/// Parse a registry JSON file into a set of value IDs (and their aliases).
fn parse_registry(json_str: &str) -> HashSet<String> {
    let v: Value = serde_json::from_str(json_str).expect("embedded registry JSON must be valid");
    let mut set = HashSet::new();
    if let Some(values) = v.get("values").and_then(|v| v.as_array()) {
        for entry in values {
            if let Some(id) = entry.get("id").and_then(|v| v.as_str()) {
                set.insert(id.to_string());
            }
            if let Some(aliases) = entry.get("aliases").and_then(|v| v.as_array()) {
                for alias in aliases {
                    if let Some(a) = alias.as_str() {
                        set.insert(a.to_string());
                    }
                }
            }
        }
    }
    set
}

// Generated by build.rs — one `const …_JSON: &str` per registry file.
// Checked into git so the crate builds standalone; regenerated on `cargo build`
// when the monorepo registry directory is present.
include!("registry_data.rs");

impl RegistryData {
    /// Load all registries from JSON embedded at compile time by `build.rs`.
    ///
    /// The build script reads each registry file from
    /// `packages/design-system-registry/registry/` and writes the contents
    /// as Rust string constants into `OUT_DIR/registry_data.rs`.
    pub fn embedded() -> Self {
        Self {
            components: parse_registry(COMPONENTS_JSON),
            states: parse_registry(STATES_JSON),
            variants: parse_registry(VARIANTS_JSON),
            sizes: parse_registry(SIZES_JSON),
            anatomy: parse_registry(ANATOMY_TERMS_JSON),
            token_objects: parse_registry(TOKEN_OBJECTS_JSON),
            structures: parse_registry(STRUCTURES_JSON),
            substructures: parse_registry(SUBSTRUCTURES_JSON),
            orientations: parse_registry(ORIENTATIONS_JSON),
            positions: parse_registry(POSITIONS_JSON),
            densities: parse_registry(DENSITIES_JSON),
            shapes: parse_registry(SHAPES_JSON),
        }
    }

    /// Look up which registry a name-object field should be validated against.
    pub fn for_field(&self, field: &str) -> Option<&HashSet<String>> {
        match field {
            "component" => Some(&self.components),
            "state" => Some(&self.states),
            "variant" => Some(&self.variants),
            "size" => Some(&self.sizes),
            "anatomy" => Some(&self.anatomy),
            "object" => Some(&self.token_objects),
            "structure" => Some(&self.structures),
            "substructure" => Some(&self.substructures),
            "orientation" => Some(&self.orientations),
            "position" => Some(&self.positions),
            "density" => Some(&self.densities),
            "shape" => Some(&self.shapes),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_registries_load() {
        let r = RegistryData::embedded();
        assert!(r.components.contains("button"));
        assert!(r.states.contains("hover"));
        assert!(r.variants.contains("accent"));
        assert!(r.sizes.contains("m"));
        assert!(r.anatomy.contains("icon"));
        assert!(r.token_objects.contains("background"));
        assert!(r.structures.contains("base"));
        assert!(r.orientations.contains("vertical"));
        assert!(r.positions.contains("top"));
        assert!(r.densities.contains("compact"));
        assert!(r.shapes.contains("uniform"));
    }

    #[test]
    fn sizes_excludes_numeric_scale() {
        let r = RegistryData::embedded();
        assert!(!r.sizes.contains("50"));
        assert!(!r.sizes.contains("100"));
        assert!(!r.sizes.contains("200"));
    }

    #[test]
    fn for_field_returns_correct_registry() {
        let r = RegistryData::embedded();
        assert!(r.for_field("component").unwrap().contains("button"));
        assert!(r.for_field("object").unwrap().contains("background"));
        assert!(r.for_field("property").is_none()); // free-form
        assert!(r.for_field("colorScheme").is_none()); // dimension
    }
}
