name: Diff PR Comment
description: Creates or updates PR comments with diff reports using shared logic

inputs:
  diff-type:
    description: "Type of diff (token, component)"
    required: true
  diff-generated:
    description: "Whether diff was generated (true/false/error)"
    required: true
  diff-content:
    description: "Generated diff content"
    required: true
  pr-number:
    description: "Pull request number"
    required: true
  github-token:
    description: "GitHub token for creating comments"
    required: true

runs:
  using: composite
  steps:
    - name: Find existing comment
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ inputs.pr-number }}
        comment-author: "github-actions[bot]"
        body-includes: "<!-- ${{ inputs.diff-type }}-diff-comment -->"
        token: ${{ inputs.github-token }}

    - name: Set comment details
      id: comment-details
      shell: bash
      run: |
        case "${{ inputs.diff-type }}" in
          "token")
            echo "emoji=ðŸŽ¨" >> $GITHUB_OUTPUT
            echo "title=Token Changes Report" >> $GITHUB_OUTPUT
            echo "description=token" >> $GITHUB_OUTPUT
            ;;
          "component")
            echo "emoji=ðŸ§©" >> $GITHUB_OUTPUT
            echo "title=Component Schema Changes Report" >> $GITHUB_OUTPUT
            echo "description=component schema" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "emoji=ðŸ“Š" >> $GITHUB_OUTPUT
            echo "title=Changes Report" >> $GITHUB_OUTPUT
            echo "description=diff" >> $GITHUB_OUTPUT
            ;;
        esac

    - name: Prepare comment content
      id: prepare-content
      shell: bash
      run: |
        # Create the comment header
        echo "<!-- ${{ inputs.diff-type }}-diff-comment -->" > /tmp/comment_body.md
        echo "## ${{ steps.comment-details.outputs.emoji }} ${{ steps.comment-details.outputs.title }}" >> /tmp/comment_body.md
        echo "" >> /tmp/comment_body.md

        if [ "${{ inputs.diff-generated }}" == "true" ]; then
          # Decode base64 content and append to file
          echo "${{ inputs.diff-content }}" | base64 -d >> /tmp/comment_body.md
        elif [ "${{ inputs.diff-generated }}" == "too-large" ]; then
          # Diff too large case
          echo "âš ï¸ **The diff output is too large to display in a PR comment.**" >> /tmp/comment_body.md
          echo "" >> /tmp/comment_body.md
          echo "${{ inputs.diff-content }}" >> /tmp/comment_body.md
          echo "" >> /tmp/comment_body.md
          echo "For large-scale changes like repository renames, please run the diff tool locally:" >> /tmp/comment_body.md
          echo '```bash' >> /tmp/comment_body.md
          echo "pnpm --filter @adobe/${{ inputs.diff-type }}-diff-generator exec -- tdiff report --otb ${{ github.base_ref }} --ntb ${{ github.head_ref }}" >> /tmp/comment_body.md
          echo '```' >> /tmp/comment_body.md
        elif [ "${{ inputs.diff-generated }}" == "false" ]; then
          # No changes case
          echo "No ${{ steps.comment-details.outputs.description }} changes detected in this pull request." >> /tmp/comment_body.md
        else
          # Error case
          echo "âš ï¸ **Error**: ${{ inputs.diff-content }}" >> /tmp/comment_body.md
          echo "" >> /tmp/comment_body.md
          echo "Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details." >> /tmp/comment_body.md
        fi

        # Add footer
        echo "" >> /tmp/comment_body.md
        echo "---" >> /tmp/comment_body.md
        echo "*This comment was automatically generated by the ${{ steps.comment-details.outputs.description }} diff tool. ðŸ¤–*" >> /tmp/comment_body.md

    - name: Create or update PR comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr-number }}
        token: ${{ inputs.github-token }}
        body-path: /tmp/comment_body.md
        edit-mode: replace
