// Copyright 2026 Adobe. All rights reserved.
// This file is licensed to you under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may obtain a copy
// of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
// OF ANY KIND, either express or implied. See the License for the specific language
// governing permissions and limitations under the License.

//! Build script: regenerates `src/registry_data.rs` from the design-system-registry
//! JSON files when building inside the monorepo. When the registry directory is absent
//! (e.g. building from a published .crate), the checked-in snapshot is used as-is.

use std::env;
use std::fs;
use std::path::PathBuf;

/// (file-stem, Rust constant name)
const REGISTRIES: &[(&str, &str)] = &[
    ("components", "COMPONENTS_JSON"),
    ("states", "STATES_JSON"),
    ("variants", "VARIANTS_JSON"),
    ("sizes", "SIZES_JSON"),
    ("anatomy-terms", "ANATOMY_TERMS_JSON"),
    ("token-objects", "TOKEN_OBJECTS_JSON"),
    ("structures", "STRUCTURES_JSON"),
    ("substructures", "SUBSTRUCTURES_JSON"),
    ("orientations", "ORIENTATIONS_JSON"),
    ("positions", "POSITIONS_JSON"),
    ("densities", "DENSITIES_JSON"),
    ("shapes", "SHAPES_JSON"),
];

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let registry_dir = manifest_dir.join("../../packages/design-system-registry/registry");
    let dest = manifest_dir.join("src/registry_data.rs");

    // When building outside the monorepo (e.g. from a published .crate), the
    // registry files won't exist. The checked-in src/registry_data.rs is used
    // as-is in that case. Check for a specific file rather than just the
    // directory to avoid false positives from unrelated paths.
    let probe = registry_dir.join(format!("{}.json", REGISTRIES[0].0));
    if !probe.is_file() {
        println!("cargo::rerun-if-changed=build.rs");
        return;
    }

    let mut generated = String::from(
        "// @generated by build.rs from packages/design-system-registry/registry/*.json\n\
         // Do not edit manually — run `cargo build` to regenerate.\n\n",
    );

    for &(stem, const_name) in REGISTRIES {
        let json_path = registry_dir.join(format!("{stem}.json"));
        let json_path = json_path
            .canonicalize()
            .unwrap_or_else(|e| panic!("registry file not found: {}: {e}", json_path.display()));

        println!("cargo::rerun-if-changed={}", json_path.display());

        let content = fs::read_to_string(&json_path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", json_path.display()));

        // Use a raw string literal with enough # to avoid clashes with JSON.
        generated.push_str(&format!("const {const_name}: &str = r##\"{content}\"##;\n"));
    }

    // Only write if contents changed, to avoid spurious rebuilds.
    let current = fs::read_to_string(&dest).unwrap_or_default();
    if current != generated {
        fs::write(&dest, generated)
            .unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
    }

    println!("cargo::rerun-if-changed=build.rs");
}
